---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ray-op-rhods-cr
rules:
- apiGroups: 
  - "mcads.codeflare.codeflare.dev" 
  - "codeflare.codeflare.dev"
  - "security.openshift.io"
  resources: 
   - mcad
   - mcads
   - securitycontextconstraints
  verbs: 
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ray-op-rhods-crb
  namespace: 'redhat-ods-operator'
subjects:
- kind: ServiceAccount
  name: rhods-operator
  namespace: 'redhat-ods-operator'
roleRef:
  kind: ClusterRole
  name: ray-op-rhods-cr
  apiGroup: rbac.authorization.k8s.io
