---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instascale-rhods-cr
rules:
- apiGroups: 
  - "codeflare.codeflare.dev" 
  resources: 
   - instascale
   - instascale/*
   - instascales
  verbs: 
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: instascale-rhods-crb
  namespace: 'redhat-ods-operator'
subjects:
- kind: ServiceAccount
  name: rhods-operator
  namespace: 'redhat-ods-operator'
roleRef:
  kind: ClusterRole
  name: instascale-rhods-cr
  apiGroup: rbac.authorization.k8s.io
